### ISSUE TITLE
faviconの作成.

### ISSUE THREAD

**Issue by ghost** [marimelon/hondaboard#36]
faviconを作成します.

**Comment by ghost** [comment]
![favicon-3D](https://user-images.githubusercontent.com/55974163/102580623-3fdc9600-4142-11eb-8bf1-30222ad0c924.png)
![favicon-pop](https://user-images.githubusercontent.com/55974163/102580692-66023600-4142-11eb-96b5-f97aa15b33f3.png)
![favicon-simple](https://user-images.githubusercontent.com/55974163/102580712-6ac6ea00-4142-11eb-9d10-81487442f13f.png)

**Comment by ghost** [comment]
3種類作ってみました.
どれが良いかを教えて下さい.
或いは,もっと良いのを作るというのであればコメントを下さい.
512×512ですが,アイコンにする際は16×16にします.

**Comment by marimelon** [comment]
無難なのは3なんだろうけど、2番を押しておこう(流石にネタすぎるか🤔

**Comment by ghost** [comment]
おｋ,とりあえず2で.

**Comment by ghost** [comment]
16×16にするとほとんど潰れるな.
