### ISSUE TITLE
ユーザマニュアルを作成する

### ISSUE THREAD

**Issue by ghost** [marimelon/hondaboard#61]
ユーザーマニュアルは完成しました.
確認をお願いします.
追加・修正項目があれば修正をお願いします.
問題なくなれば,issueを閉じてください.

**Comment by marimelon** [comment]
ユーザマニュアルの各ページの説明ですが下記のような表示のほうが見やすいと思うのですがどうでしょうか

![image](https://user-images.githubusercontent.com/29140293/104810457-04fc7980-5838-11eb-9c81-9b904e64f26c.png)

**Comment by ghost** [comment]
図の番号との対応だから,①の方がいい.
