### ISSUE TITLE
プレゼンテーション資料の作成.

### ISSUE THREAD

**Issue by ghost** [marimelon/hondaboard#62]
プレゼンテーション資料は完成しました.
確認をお願いします.
追加・修正項目があれば修正をお願いします.
問題なくなれば,issueを閉じてください.

**Comment by marimelon** [comment]
目次いらなくね？

**Comment by ghost** [comment]
無くてもいいよ.
なんとなくと,Giithub上で見る分にはあった方が綺麗かなって思っただけだから.

**Comment by ghost** [comment]
一応,一通りできたから,Googleドライブにプレゼン資料上げて,フォームに解答はしておいた.

**Comment by ghost** [comment]
発表前日が締め切りだから,それまでに閉じれる様に頼む.
全部閉じられたら,ドライブに上げた資料も更新しておく.

**Comment by ghost** [comment]
全部閉じられたから,ドライブに上げた資料更新しといた.
